#!/bin/env bash

MODEL=roberta-large
EPOCHS=6
LOSS=lsce

python main.py \
    --train \
    --eval \
    --lr=1e-5 \
    --data-dir=/tmp \
    --model-dir=roberta-lg-sentiment \
    --model-name=$MODEL \
    --epochs=$EPOCHS \
    --loss=$LOSS \
    --batch-size=32 \